#! /usr/bin/env python
# emacs: -*- mode: python; py-indent-offset: 4; indent-tabs-mode: nil -*-
# vi: set ft=python sts=4 ts=4 sw=4 et:

import os
import util

username = 'root'
passwd = util.read_root_pwd('root_pwd')
hosts = util.read_hoststab('hoststab')
admin_hostname = util.hostname()
host_list = [hosts[name] for name in hosts if not name == admin_hostname]

for host in host_list:
    util.ssh2killall(host, username, passwd)

